version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: property_scraper
      POSTGRES_USER: scraper
      POSTGRES_PASSWORD: scraper_password
      POSTGRES_MAX_CONNECTIONS: 100
      POSTGRES_SHARED_BUFFERS: 4GB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scraper -d property_scraper"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 8G
    command: 
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "shared_buffers=4GB"
      - "-c"
      - "work_mem=128MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "effective_cache_size=6GB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "checkpoint_timeout=30min"
      - "-c"
      - "max_wal_size=2GB"
      - "-c"
      - "min_wal_size=1GB"

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://scraper:scraper_password@db:5432/property_scraper
      SECRET_KEY: your-secret-key-here
    deploy:
      resources:
        limits:
          memory: 2G

  scraper:
    build:
      context: .
      dockerfile: docker/scraper/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://scraper:scraper_password@db:5432/property_scraper
      SCRAPE_INTERVAL: 60
    restart: unless-stopped
    ports:
      - "5900:5900"
    volumes:
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 2G

volumes:
  postgres_data: 