version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: property_scraper
      POSTGRES_USER: scraper
      POSTGRES_PASSWORD: scraper_password
      MAX_PAGES_PER_LOCATION: -1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scraper -d property_scraper"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://scraper:scraper_password@db:5432/property_scraper
      SECRET_KEY: your-secret-key-here

  scraper:
    build:
      context: .
      dockerfile: docker/scraper/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://scraper:scraper_password@db:5432/property_scraper
      SCRAPE_INTERVAL: 60
    restart: unless-stopped
    ports:
      - "5900:5900"
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data: 